### ISSUE TITLE
Publishing a solution to the challenge

### ISSUE THREAD

**Issue by SimonMarechal** [forumcrack/forumcrack.github.io#1]
Hello!

I am in the process of writing some articles related to writing a (toy) symbolic execution engine, and I am using this as the main example. Is that OK? How far can I go (including the .wasm in the github repo, posting the solution in the article, etc.) ?

**Comment by forumcrack** [comment]
Hello @SimonMarechal !

My apologies for the late reply, I hadn't checked the e-mail associated to this account for a while.

> I am in the process of writing some articles related to writing a (toy) symbolic execution engine, and I am using this as the main example. Is that OK? How far can I go (including the .wasm in the github repo, posting the solution in the article, etc.) ?

No problem. Don't hesitate to use the content of this repo however you want.
I see that you have already published [some](https://www.synacktiv.com/en/publications/writing-a-toy-symbolic-interpreter-and-solving-challenges-part-1) [very](https://www.synacktiv.com/en/publications/writing-a-toy-symbolic-interpreter-and-solving-challenges-part-2) [interesting](https://www.synacktiv.com/en/publications/writing-a-toy-symbolic-interpreter-and-solving-challenges-part-3) [articles](https://www.synacktiv.com/en/publications/writing-a-toy-symbolic-interpreter-and-solving-challenges-part-4) explaining how symbolic execution engines work. I guess that's the perfect opportunity for me to finally learn a bit of Haskell so I can fully understand them :-)

I'm glad this little challenge was a useful example. Thanks a lot for your great articles!

**Comment by SimonMarechal** [comment]
Yay, I will update the repo so that it is easier to test the interpreter, thanks a lot!
